confirm-before-quit = false
copy-on-select = true
hide-mouse-cursor-when-typing = true
theme = "catppuccin_macchiato"

[adaptive-theme]
light = "catppuccin_latte"
dark = "catppuccin_macchiato"

[editor]
program = "/run/current-system/sw/bin/hx"

[effects]
trail-cursor = true

[fonts]
size = 18
family = "JetBrainsMono Nerd Font"

[navigation]
mode = "Tab"

[shell]
program = "/run/current-system/sw/bin/fish"
