theme = "catppuccin_macchiato"

[editor]
color-modes = true
cursorline = true
end-of-line-diagnostics = "hint"
line-number = "relative"
mouse = false
rulers = [80]
scrolloff = 0
true-color = true

[editor.indent-guides]
render = true

[editor.inline-diagnostics]
cursor-line = "warning"
